### PR TITLE
Handle empty gzip responses with content-length > 0

### LINKED ISSUE #253: HEAD fails on compressed response
```
$ xh head httpbin.org/gzip
[...]
xh: error: error decoding gzip response body: failed to fill whole buffer
```
This didn't happen before #241, so reqwest deals with it correctly. I don't know how.

### PR DESCRIPTION
**Pull request by ducaale**
Resolves #253

### CODE REVIEW

File: src/decoder.rs [hunk 1]
```diff
@@ -86,36 +92,33 @@ impl<R: Read> Read for Decoder<R> {
...
-                    io::Error::new(
-                        e.kind(),
-                        format!("error decoding brotli response body: {}", e),
-                    )
-                }
-            }),
+            Decoder::Gzip(decoder) => match decoder.read(buf) {
+                Ok(n) => Ok(n),
+                Err(e) if decoder.get_ref().has_errored => Err(e),
+                Err(_) if !decoder.get_ref().has_read_data => Ok(0),
```
Comment (ducaale) [inline src/decoder.rs:98]: The check has to be done in this order to avoid ignoring `InnerReader` errors when no data has been read

**Review by blyxxyz — APPROVED** [review]
Works great!
