### PR TITLE
Don't fail on error code 416 if resuming download

### LINKED ISSUE #433: Errors if file is already downloaded, even with `--continue`
when downloading a file for the first time, or resuming a partial download, the `--continue` option works as i would expect. however, if the download has already completely finished, the server may respond with a `416: Range Not Satisfiable`, which causes the command to fail with error code `4`. this is a bit strange because conceptually the command *hasn't* failed, the file is already downloaded so it should simply do nothing.

my use-case is a shell script that downloads a bunch of files. if a download fails, i want the entire script to stop, rather than continuing to try every remaining file. however, if the script is interrupted in the middle, i want to be able to resume the downloads by re-running the script.

[curl has a special case for this](https://github.com/curl/curl/blob/3696ac4e29836dd3e5e3b2101d53294846a6ec1b/lib/http.c#L1146C3-L1152C18), which i think is the ideal behavior.

## example

```bash
xh --verbose --download --continue --output "file.png" "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/HTTP_logo.svg/2560px-HTTP_logo.svg.png"
```

<details>

<summary>creating new file</summary>

```
GET /wikipedia/commons/thumb/5/5b/HTTP_logo.svg/2560px-HTTP_logo.svg.png HTTP/1.1
Accept: */*
Accept-Encoding: identity
Connection: keep-alive
Host: upload.wikimedia.org
User-Agent: xh/0.25.0

HTTP/2.0 200 OK
accept-ranges: bytes
access-control-allow-origin: *
access-control-expose-headers: Age, Date, Content-Length, Content-Range, X-Content-Duration, X-Cache
age: 28322
content-disposition: inline;filename*=UTF-8''HTTP_logo.svg.png
content-length: 65512
content-type: image/png
date: Mon, 24 Nov 2025 09:27:56 GMT
etag: 260f44898392febabafd7bc8eb417476
last-modified: Tue, 09 Jul 2024 18:21:46 GMT
nel: { "report_to": "wm_nel", "max_age": 604800, "failure_fraction": 0.05, "success_fraction": 0.0}
report-to: { "group": "wm_nel", "max_age": 604800, "endpoints": [{ "url": "https://intake-logging.wikimedia.org/v1/events?stream=w3c.reportingapi.network_error&schema_uri=/w3c/reportingapi/network_error/1.0.0" }] }
server: envoy
server-timing: cache;desc="hit-front", host;desc="cp2042"
set-cookie: WMF-Uniq=erjG37AcAzNyh03ncTm91QK1AAAAAFvdkCTOg1TnkH-O8W-NSFB958ypARXLkLHg;Domain=upload.wikimedia.org;Path=/;HttpOnly;secure;SameSite=None;Expires=Tue, 24 Nov 2026 00:00:00 GMT
strict-transport-security: max-age=106384710; includeSubDomains; preload
timing-allow-origin: *
x-cache: cp2040 hit, cp2042 hit/3
x-cache-status: hit-front
x-client-ip: 135.26.81.7
x-content-type-options: nosniff
x-request-id: 2dfdcfc0-d46f-4543-969d-06c214ca6da3

Downloading 63.98 KiB to "file.png"
Done. 63.98 KiB in 0.01684s (3.71 MiB/s)
```

</details>

<details>

<summary>entire file already exists</summary>

```
GET /wikipedia/commons/thumb/5/5b/HTTP_logo.svg/2560px-HTTP_logo.svg.png HTTP/1.1
Accept: */*
Accept-Encoding: identity
Connection: keep-alive
Host: upload.wikimedia.org
Range: bytes=65512-
User-Agent: xh/0.25.0

HTTP/2.0 416 Range Not Satisfiable
accept-ranges: bytes
access-control-allow-origin: *
access-control-expose-headers: Age, Date, Content-Length, Content-Range, X-Content-Duration, X-Cache
age: 28323
content-disposition: inline;filename*=UTF-8''HTTP_logo.svg.png
content-length: 0
content-range: bytes */65512
content-type: image/png
date: Mon, 24 Nov 2025 09:27:56 GMT
etag: 260f44898392febabafd7bc8eb417476
last-modified: Tue, 09 Jul 2024 18:21:46 GMT
nel: { "report_to": "wm_nel", "max_age": 604800, "failure_fraction": 0.05, "success_fraction": 0.0}
report-to: { "group": "wm_nel", "max_age": 604800, "endpoints": [{ "url": "https://intake-logging.wikimedia.org/v1/events?stream=w3c.reportingapi.network_error&schema_uri=/w3c/reportingapi/network_error/1.0.0" }] }
server: envoy
server-timing: cache;desc="hit-front", host;desc="cp2042"
set-cookie: WMF-Uniq=HRodHntpTPFLvBoAqYgK-gK1AAAAAFvduIkgG7X1MSK8-zq7gvObv_FXZGIslqdV;Domain=upload.wikimedia.org;Path=/;HttpOnly;secure;SameSite=None;Expires=Tue, 24 Nov 2026 00:00:00 GMT
strict-transport-security: max-age=106384710; includeSubDomains; preload
timing-allow-origin: *
x-cache: cp2040 hit, cp2042 hit/4
x-cache-status: hit-front
x-client-ip: 135.26.81.7
x-content-type-options: nosniff
x-request-id: 2ae221d3-6eab-4d77-be7a-db787faaa9ce
```

</details>

---

P.S. the current behavior does match HTTPie, which has [this similar-but-not-quite-the-same bug report](https://github.com/httpie/cli/issues/842)

### PR DESCRIPTION
**Pull request by simonomi**
fixes #433

### CODE REVIEW

**Comment by blyxxyz** [comment]
Looks good so far. Could you add a test case?

File: tests/cli.rs [hunk 1]
```diff
@@ -3817,3 +3817,40 @@ fn reason_phrase_is_preserved() {
...
+            .body("".into())
+            .unwrap()
+    });
+    
+    get_command()
+        .arg(server.base_url())
+        .arg("--download")
+        .args(["--output", "/dev/null"])
+        .assert()
+        .failure();
```
Comment (blyxxyz) [inline tests/cli.rs]: Can you also check the exit status (`.code(4)`) and check that stderr is empty to make sure that it didn't fail in some unexpected other way?

File: tests/cli.rs
Comment (blyxxyz) [inline tests/cli.rs]: Can you move these cases to `tests/cases/download.rs`?

**Review by blyxxyz — APPROVED** [review]
Works great!

File: tests/cli.rs [hunk 2]
```diff
@@ -3817,3 +3817,44 @@ fn reason_phrase_is_preserved() {
...
+            .body("".into())
+            .unwrap()
+    });
+
+    get_command()
+        .arg(server.base_url())
+        .arg("--download")
+        .args(["--output", "downloaded_file.png"])
+        .assert()
+        .failure();
```
[the remark this answers is not in the document]
Comment (simonomi) [reply tests/cli.rs]: in this case, stderr *should* have an error, right? it's only when passing `--continue` that the error is suppressed (and even then, the 416 is still shown, just without an error code)
